# Generated by Django 3.1.7 on 2021-03-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodMenu', '0003_auto_20210331_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['id'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locals'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
