# Generated by Django 3.1.7 on 2021-03-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodMenu', '0004_auto_20210331_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categories',
            field=models.ManyToManyField(related_name='locals', through='foodMenu.MenuCategory', to='foodMenu.Category'),
        ),
    ]
