# Generated by Django 3.1.7 on 2021-04-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodMenu', '0005_auto_20210331_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu_cat',
            field=models.ManyToManyField(related_name='products', to='foodMenu.MenuCategory'),
        ),
    ]
